"""Small, exact finite groups represented by multiplication tables.

Only the Python standard library is used.  The constructors are deliberately
explicit: every returned object is checked against the group axioms before it
is used by the graph routines.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from itertools import permutations, product
from typing import Callable, Dict, Iterable, List, Sequence, Tuple


@dataclass
class FiniteGroup:
    """A finite group with elements named by distinct strings.

    ``table[i][j]`` is the index of the product of elements ``i`` and ``j``.
    Indices, rather than user-facing labels, are used by all exact algorithms.
    """

    group_id: str
    elements: Tuple[str, ...]
    table: Tuple[Tuple[int, ...], ...]

    def __post_init__(self) -> None:
        self.index: Dict[str, int] = {label: i for i, label in enumerate(self.elements)}
        if len(self.index) != len(self.elements):
            raise ValueError("element labels must be distinct")
        self.identity = self._find_identity()

    @classmethod
    def from_operation(
        cls,
        group_id: str,
        raw_elements: Sequence[object],
        operation: Callable[[object, object], object],
        label: Callable[[object], str] = str,
    ) -> "FiniteGroup":
        raw = tuple(raw_elements)
        raw_index = {x: i for i, x in enumerate(raw)}
        if len(raw_index) != len(raw):
            raise ValueError("raw elements must be distinct and hashable")
        table: List[Tuple[int, ...]] = []
        for x in raw:
            row = []
            for y in raw:
                z = operation(x, y)
                if z not in raw_index:
                    raise ValueError("operation is not closed")
                row.append(raw_index[z])
            table.append(tuple(row))
        return cls(group_id, tuple(label(x) for x in raw), tuple(table))

    @property
    def order(self) -> int:
        return len(self.elements)

    def _find_identity(self) -> int:
        n = len(self.elements)
        if n == 0:
            raise ValueError("a group must be nonempty")
        identities = [
            e
            for e in range(n)
            if all(self.table[e][x] == x and self.table[x][e] == x for x in range(n))
        ]
        if len(identities) != 1:
            raise ValueError("multiplication table does not have a unique identity")
        return identities[0]

    def validate(self, check_associativity: bool = True) -> None:
        """Raise ``ValueError`` unless the table satisfies the group axioms."""

        n = self.order
        if len(self.table) != n or any(len(row) != n for row in self.table):
            raise ValueError("multiplication table has the wrong dimensions")
        if any(value < 0 or value >= n for row in self.table for value in row):
            raise ValueError("multiplication table contains an invalid index")
        e = self.identity
        for x in range(n):
            if not any(self.table[x][y] == e and self.table[y][x] == e for y in range(n)):
                raise ValueError("element has no two-sided inverse")
        if check_associativity:
            for x in range(n):
                for y in range(n):
                    xy = self.table[x][y]
                    for z in range(n):
                        if self.table[xy][z] != self.table[x][self.table[y][z]]:
                            raise ValueError("multiplication is not associative")

    def multiply(self, x: int, y: int) -> int:
        return self.table[x][y]

    def commute(self, x: int, y: int) -> bool:
        return self.table[x][y] == self.table[y][x]

    def inverse(self, x: int) -> int:
        e = self.identity
        return next(y for y in range(self.order) if self.table[x][y] == e and self.table[y][x] == e)

    def center(self) -> Tuple[int, ...]:
        return tuple(x for x in range(self.order) if all(self.commute(x, y) for y in range(self.order)))

    def generated_subgroup(self, generators: Iterable[int]) -> Tuple[int, ...]:
        """Return the subgroup generated by ``generators``, by exact closure."""

        subgroup = {self.identity}
        subgroup.update(generators)
        changed = True
        while changed:
            changed = False
            current = tuple(subgroup)
            for x in current:
                subgroup.add(self.inverse(x))
                for y in current:
                    subgroup.add(self.table[x][y])
            if len(subgroup) != len(current):
                changed = True
        return tuple(sorted(subgroup))

    def is_subgroup(self, subset: Iterable[int]) -> bool:
        values = frozenset(subset)
        if self.identity not in values:
            return False
        return all(self.table[x][y] in values for x in values for y in values)

    def is_abelian_subset(self, subset: Iterable[int]) -> bool:
        values = tuple(subset)
        return all(self.commute(x, y) for i, x in enumerate(values) for y in values[i + 1 :])

    def center_cosets(self) -> Tuple[Tuple[int, ...], ...]:
        """Return the (left) cosets of the center in deterministic order."""

        center = self.center()
        unseen = set(range(self.order))
        cosets = []
        while unseen:
            representative = min(unseen)
            coset = tuple(sorted(self.table[representative][z] for z in center))
            cosets.append(coset)
            unseen.difference_update(coset)
        return tuple(cosets)

    def all_subgroups(self) -> Tuple[Tuple[int, ...], ...]:
        """Enumerate all subgroups by adjoining one element at a time.

        This is intended for small certification examples, not group-database
        scale enumeration.
        """

        trivial = (self.identity,)
        seen = {frozenset(trivial)}
        queue = deque([trivial])
        while queue:
            subgroup = queue.popleft()
            values = set(subgroup)
            for element in range(self.order):
                if element in values:
                    continue
                extension = self.generated_subgroup(tuple(subgroup) + (element,))
                key = frozenset(extension)
                if key not in seen:
                    seen.add(key)
                    queue.append(extension)
        ordered = sorted((tuple(sorted(x)) for x in seen), key=lambda x: (len(x), x))
        return tuple(ordered)


def cyclic_group(n: int) -> FiniteGroup:
    if n < 1:
        raise ValueError("cyclic group order must be positive")
    return FiniteGroup.from_operation(
        "C%d" % n,
        tuple(range(n)),
        lambda x, y: (x + y) % n,
        lambda x: "1" if x == 0 else "g^%d" % x,
    )


def _cycle_label(permutation: Tuple[int, ...]) -> str:
    n = len(permutation)
    visited = [False] * n
    cycles = []
    for start in range(n):
        if visited[start]:
            continue
        cycle = []
        current = start
        while not visited[current]:
            visited[current] = True
            cycle.append(current + 1)
            current = permutation[current]
        if len(cycle) > 1:
            cycles.append("(" + " ".join(str(x) for x in cycle) + ")")
    return "1" if not cycles else "".join(cycles)


def symmetric_group(n: int) -> FiniteGroup:
    if n < 1:
        raise ValueError("symmetric group degree must be positive")
    values = tuple(permutations(range(n)))

    def compose(left: object, right: object) -> Tuple[int, ...]:
        p = left  # type: ignore[assignment]
        q = right  # type: ignore[assignment]
        return tuple(p[q[i]] for i in range(n))  # type: ignore[index]

    return FiniteGroup.from_operation("S%d" % n, values, compose, _cycle_label)


def dihedral_group(rotation_order: int) -> FiniteGroup:
    """Return D_(2n)=<r,s | r^n=s^2=1, srs=r^-1>."""

    n = rotation_order
    if n < 2:
        raise ValueError("rotation order must be at least two")
    values = tuple(product(range(n), range(2)))

    def multiply(left: object, right: object) -> Tuple[int, int]:
        i, j = left  # type: ignore[misc]
        k, ell = right  # type: ignore[misc]
        return ((i + (-1 if j else 1) * k) % n, (j + ell) % 2)

    def label(value: object) -> str:
        i, j = value  # type: ignore[misc]
        if i == 0 and j == 0:
            return "1"
        rotation = "" if i == 0 else ("r" if i == 1 else "r^%d" % i)
        reflection = "s" if j else ""
        return rotation + reflection

    return FiniteGroup.from_operation("D%d" % (2 * n), values, multiply, label)


def quaternion_group() -> FiniteGroup:
    """Return Q8 with labels 1,-1,i,-i,j,-j,k,-k."""

    values = tuple((sign, basis) for basis in range(4) for sign in (1, -1))
    # (resulting sign, resulting basis), before multiplying input signs.
    basis_table = (
        ((1, 0), (1, 1), (1, 2), (1, 3)),
        ((1, 1), (-1, 0), (1, 3), (-1, 2)),
        ((1, 2), (-1, 3), (-1, 0), (1, 1)),
        ((1, 3), (1, 2), (-1, 1), (-1, 0)),
    )

    def multiply(left: object, right: object) -> Tuple[int, int]:
        sign1, basis1 = left  # type: ignore[misc]
        sign2, basis2 = right  # type: ignore[misc]
        sign3, basis3 = basis_table[basis1][basis2]
        return (sign1 * sign2 * sign3, basis3)

    def label(value: object) -> str:
        sign, basis = value  # type: ignore[misc]
        name = ("1", "i", "j", "k")[basis]
        return name if sign == 1 else "-" + name

    return FiniteGroup.from_operation("Q8", values, multiply, label)


def heisenberg_group(prime: int) -> FiniteGroup:
    """Unitriangular 3-by-3 matrices over F_p, for a prime p.

    Elements are triples (a,b,c), denoting the upper entries (1,2), (2,3),
    and (1,3).  Primality is checked by trial division.
    """

    p = prime
    if p < 2 or any(p % divisor == 0 for divisor in range(2, int(p ** 0.5) + 1)):
        raise ValueError("parameter must be prime")
    values = tuple(product(range(p), repeat=3))

    def multiply(left: object, right: object) -> Tuple[int, int, int]:
        a, b, c = left  # type: ignore[misc]
        x, y, z = right  # type: ignore[misc]
        return ((a + x) % p, (b + y) % p, (c + z + a * y) % p)

    return FiniteGroup.from_operation(
        "Heis%d" % p,
        values,
        multiply,
        lambda value: "(%d,%d,%d)" % value,  # type: ignore[arg-type]
    )


def extraspecial_two_group(rank: int) -> FiniteGroup:
    """Return the order 2^(1+2m) extraspecial group E_m, m=``rank``.

    Elements are triples ``(a,b,c)`` with ``a,b`` binary vectors of length m
    and ``c`` in F_2.  Multiplication uses the cocycle ``a dot b'``.  Its
    commutator pairing on the quotient by the center is the standard symplectic
    form ``a dot b' + a' dot b``.
    """

    return extraspecial_prime_group(2, rank, "E%d" % rank)


def extraspecial_prime_group(prime: int, rank: int, group_id: str = "") -> FiniteGroup:
    """Return an extraspecial group of order ``p^(1+2m)``.

    Elements are triples ``(a,b,c)`` with ``a,b`` in ``F_p^m`` and central
    coordinate ``c`` in ``F_p``. Multiplication uses the scalar cocycle
    ``a dot b'``. Its commutator form on the quotient by the center is
    ``a dot b' - a' dot b``. For ``p=2`` this agrees with the E_m constructor
    above; for odd p it is the exponent-p extraspecial group.
    """

    p, m = prime, rank
    if p < 2 or any(p % divisor == 0 for divisor in range(2, int(p ** 0.5) + 1)):
        raise ValueError("prime must be prime")
    if m < 1:
        raise ValueError("rank must be positive")
    vectors = tuple(product(range(p), repeat=m))
    values = tuple((a, b, c) for a in vectors for b in vectors for c in range(p))

    def vector_label(vector: Sequence[int]) -> str:
        separator = "" if p < 11 else ","
        return separator.join(str(x) for x in vector)

    def multiply(left: object, right: object) -> Tuple[Tuple[int, ...], Tuple[int, ...], int]:
        a, b, c = left  # type: ignore[misc]
        x, y, z = right  # type: ignore[misc]
        return (
            tuple((u + v) % p for u, v in zip(a, x)),
            tuple((u + v) % p for u, v in zip(b, y)),
            (c + z + sum(u * v for u, v in zip(a, y))) % p,
        )

    return FiniteGroup.from_operation(
        group_id or "E_p%d_m%d" % (p, m),
        values,
        multiply,
        lambda value: "(%s;%s;%d)"
        % (
            vector_label(value[0]),  # type: ignore[arg-type,index]
            vector_label(value[1]),  # type: ignore[arg-type,index]
            value[2],  # type: ignore[index]
        ),
    )


def direct_product(left: FiniteGroup, right: FiniteGroup, group_id: str = "") -> FiniteGroup:
    """Return the external direct product of two table groups."""

    pairs = tuple(product(range(left.order), range(right.order)))

    def multiply(x: object, y: object) -> Tuple[int, int]:
        a, b = x  # type: ignore[misc]
        c, d = y  # type: ignore[misc]
        return (left.table[a][c], right.table[b][d])

    return FiniteGroup.from_operation(
        group_id or "%sx%s" % (left.group_id, right.group_id),
        pairs,
        multiply,
        lambda pair: "(%s,%s)" % (left.elements[pair[0]], right.elements[pair[1]]),  # type: ignore[index]
    )


def named_group(specification: str) -> FiniteGroup:
    """Parse the small deterministic group vocabulary used by configs."""

    if "x" in specification:
        factors = specification.split("x")
        result = named_group(factors[0])
        for factor in factors[1:]:
            result = direct_product(result, named_group(factor))
        result.group_id = specification
        return result
    if specification.startswith("C"):
        return cyclic_group(int(specification[1:]))
    if specification.startswith("D"):
        order = int(specification[1:])
        if order % 2:
            raise ValueError("dihedral group order must be even")
        return dihedral_group(order // 2)
    if specification == "Q8":
        return quaternion_group()
    if specification.startswith("S"):
        return symmetric_group(int(specification[1:]))
    if specification.startswith("Heis"):
        return heisenberg_group(int(specification[4:]))
    if specification.startswith("E"):
        return extraspecial_two_group(int(specification[1:]))
    raise ValueError("unknown group specification: %s" % specification)
